name: Crypto Alert

on:
  schedule:
    - cron: '0 * * * *'  # اجرای هر یک ساعت یک‌بار (در دقیقه ۰ هر ساعت)
  push:  # اجرای آنی به‌محض اضافه یا تغییر در فایل workflow یا کد
    branches:
      - main
  workflow_dispatch:  # امکان اجرای دستی

jobs:
  crypto-alert:
    runs-on: ubuntu-22.04  # مشخص کردن نسخه سیستم‌عامل

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # دریافت کد از مخزن

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"  # نسخه پایتون مورد نیاز

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ccxt pandas mplfinance  # نصب کتابخانه‌ها

    - name: Run script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}  # ایمیل فرستنده
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}  # ایمیل گیرنده
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # رمز ایمیل
      run: |
        python main.py  # اجرای فایل پایتون
